Description of plotGUI
FIRA / gui / plotGUI.m
plotGUI
PURPOSE
plotGUI Application M-file for plotGUI.fig
SYNOPSIS
function varargout = plotGUI(varargin)
DESCRIPTION
 plotGUI Application M-file for plotGUI.fig
    FIG = plotGUI launch plotGUI GUI.
    plotGUI('callback_name', ...) invoke the named callback.
 This is the main gui for analyzing FIRA data files
CROSS-REFERENCE INFORMATION
This function calls:
buildFIRA_purge function buildFIRA_purge
bConnect function bConnect(spm, spike_list, sig_list, ...
bConnect_loop function bConnect_loop
bFile function bFile(file_in, file_type, spm, file_out, spike_list, ...
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
getGUI_FIRAparams function params_ = getGUI_FIRAparams
openFIRA function openFIRA(filename, include_list, exclude_list)
saveFIRA function saveFIRA(filename)
This function is called by: