Description of getFIRA_ecodesByName
FIRA / utilities / getFIRA_ecodesByName.m
getFIRA_ecodesByName
PURPOSE
function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
SYNOPSIS
function ecodes_ = getFIRA_ecodesByName(name, type, trials)
DESCRIPTION
 function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
 gets an array of ecodes (times, ids, or values) from FIRA.ecodes.data
 Arguments:
   name    ... column name (required)
   type    ... column type ('time', 'id', or 'value') (optional)
   trials  ... selection array of trials (optional)
 Returns:
   array of ecodes
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plotGUI_deviations plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
plotGUI_neurometricROCT plotGUI_neurometricROC Application M-file for plotGUI_neurometricROCT.fig
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_quickT plotGUI_quickT Application M-file for plotGUI_quickT.fig
gsGUI_ecodeIDsByName function varargout = gsGUI_ecodeIDsByName(key, varargin)
gsGUI_ecodeTimesByName function varargout = gsGUI_ecodeTimesByName(key, varargin)
gsGUI_ecodeValuesByName function varargout = gsGUI_ecodeValuesByName(key, varargin)