Description of getFIRA_ec
FIRA / utilities / getFIRA_ec.m
getFIRA_ec
PURPOSE
function ecs_ = getFIRA_ec(trial, names)
SYNOPSIS
function ecs_ = getFIRA_ec(trial, names)
DESCRIPTION
 function ecs_ = getFIRA_ec(trial, names)
 Utility function for getting the value
   from FIRA.ecodes.data, by name and trial #
CROSS-REFERENCE INFORMATION
This function calls:
trial (trial) function tr_ = trial(varargin)
This function is called by:
spm700 function spm700(func)
spm724 function spm724(func)
spm724j function spm724(func)
spm724s function spm724s(func)
plotGUI_deviations plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
getFIRA_ROCsequence function [rocs_, bins_] = getFIRA_ROCsequence(...
getFIRA_spikeEpochs function [rocs_, bins_] = getFIRA_ROCsequence(...
showFIRA_saccades function showFIRA_saccades(trial, fig)