Description of getFIRA_ecodeColumnByName
FIRA / utilities / getFIRA_ecodeColumnByName.m
getFIRA_ecodeColumnByName
PURPOSE
function column_ = getFIRA_ecodeColumnByName(name, type)
SYNOPSIS
function column_ = getFIRA_ecodeColumnByName(name, type)
DESCRIPTION
 function column_ = getFIRA_ecodeColumnByName(name, type)
 gets the column number from FIRA that matches the name and type.
 the 'type' argument is recommended but is only essential if the 'name'
 appears in more than one trial field.
 names: 'sid' 'correct' 'stim'  etc
 types: 'id' 'value' 'time'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spm724 function spm724(func)
spm724j function spm724(func)
gsGUI_selectTrials function varargout = gsGUI_selectTrials(varargin)
addFIRA_tc function addFIRA_tc(params, reps, randomize_flag)
getFIRA_uniqueEcodeValues function ids_ = getFIRA_uniqueEcodeIDs(names)