Description of openFIRA
FIRA / utilities / openFIRA.m
openFIRA
PURPOSE
function openFIRA(filename, include_list, exclude_list)
SYNOPSIS
function openFIRA(filename, include_list, exclude_list)
DESCRIPTION
 function openFIRA(filename, include_list, exclude_list)
 Convenience routine for opening a 'mat' file
 containing a FIRA data structure
 optional arguments specify which fields to include/exclude
CROSS-REFERENCE INFORMATION
This function calls:
convertFIRA function convertFIRA
This function is called by:
plotGUI plotGUI Application M-file for plotGUI.fig
combineFIRA_files function combineFIRA_files(fileout, varargin)