Description of setFIRA_ec
FIRA / utilities / setFIRA_ec.m
setFIRA_ec
PURPOSE
function setFIRA_ec(trial, names, values)
SYNOPSIS
function setFIRA_ec(trial, names, values)
DESCRIPTION
 function setFIRA_ec(trial, names, values)
 Utility function for setting an ecode
CROSS-REFERENCE INFORMATION
This function calls:
trial (trial) function tr_ = trial(varargin)
This function is called by:
spm700 function spm700(func)
spm724 function spm724(func)
spm724j function spm724(func)
spm724s function spm724s(func)