Description of plotGUI_summary
FIRA / gui/ plotMenu / plotGUI_summary.m
plotGUI_summary
PURPOSE
plotGUI_summary Application M-file for plotGUI_summary.fig
SYNOPSIS
function varargout = plotGUI_summary(varargin)
DESCRIPTION
 plotGUI_summary Application M-file for plotGUI_summary.fig
 Usage:
    FIG = plotGUI_summary({<deleteFcn>})
       launch plotGUI_summary GUI.
    plotGUI_summary('callback_name', ...) invoke the named callback.
 wrapper GUI for plotGUI_summary
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
gsGUI_analogByName function varargout = gsGUI_analogByName(key, varargin)
gsGUI_ecodeIDsByName function varargout = gsGUI_ecodeIDsByName(key, varargin)
gsGUI_ecodeTimesByName function varargout = gsGUI_ecodeTimesByName(key, varargin)
gsGUI_ecodeValuesByName function varargout = gsGUI_ecodeValuesByName(key, varargin)
gsGUI_spikeByID function varargout = gsGUI_spikeByID(key, varargin)
This function is called by: