Description of plotGUI_raster
FIRA / gui/ plotMenu / plotGUI_raster.m
plotGUI_raster
PURPOSE
plotGUI_rasterTC Application M-file for plotGUI_raster.fig
SYNOPSIS
function varargout = plotGUI_raster(varargin)
DESCRIPTION
 plotGUI_rasterTC Application M-file for plotGUI_raster.fig
 Usage:
    FIG = plotGUI_rasterTC({<deleteFcn>})
       launch plotGUI_rasterTC GUI.
    plotGUI_rasterTC('callback_name', ...) invoke the named callback.
 wrapper GUI for plotGUI_raster
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
plotGUI_raster plotGUI_rasterTC Application M-file for plotGUI_raster.fig
getGUI_pmString string_ = getGUI_pmString(menu_handle)
gsGUI_ecodeTimesByName function varargout = gsGUI_ecodeTimesByName(key, varargin)
gsGUI_saveSettings
gsGUI_selectByUniqueID function varargout = gsGUI_selectByUniqueID(key, varargin)
gsGUI_selectTrials function varargout = gsGUI_selectTrials(varargin)
gsGUI_spikeByID function varargout = gsGUI_spikeByID(key, varargin)
plotFIRA_rasterPSTH function stats_ = plotFIRA_rasterPSTH(trials, Lsb, spikei, ...
This function is called by:
plotGUI_raster plotGUI_rasterTC Application M-file for plotGUI_raster.fig