Description of plotGUI_neurometricROC
FIRA / gui/ plotMenu / plotGUI_neurometricROC.m
plotGUI_neurometricROC
PURPOSE
plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
SYNOPSIS
function varargout = plotGUI_neurometricROC(varargin)
DESCRIPTION
 plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
 Usage:
    FIG = plotGUI_neurometricROC({<deleteFcn>})
       launch plotGUI_neurometricROC GUI.
    plotGUI_neurometricROC('callback_name', ...) invoke the named callback.
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
gsGUI_ecodeTimesByName function varargout = gsGUI_ecodeTimesByName(key, varargin)
gsGUI_saveSettings
gsGUI_selectByUniqueID function varargout = gsGUI_selectByUniqueID(key, varargin)
gsGUI_selectTrials function varargout = gsGUI_selectTrials(varargin)
gsGUI_spikeByID function varargout = gsGUI_spikeByID(key, varargin)
getFIRA_ecodesByName function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
plotFIRA_neurometricROC function [fits_, stats_] = plotFIRA_neurometricROC(...
This function is called by:
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig