Description of plotGUI_psychometric
FIRA / gui/ plotMenu / plotGUI_psychometric.m
plotGUI_psychometric
PURPOSE
plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
SYNOPSIS
function varargout = plotGUI_psychometric(varargin)
DESCRIPTION
 plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
 Usage:
    FIG = plotGUI_psychometric({<deleteFcn>})
       launch plotGUI_psychometric GUI.
    plotGUI_psychometric('callback_name', ...) invoke the named callback.
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
gsGUI_ecodeTimesByName function varargout = gsGUI_ecodeTimesByName(key, varargin)
gsGUI_saveSettings
gsGUI_selectByUniqueID function varargout = gsGUI_selectByUniqueID(key, varargin)
gsGUI_selectTrials function varargout = gsGUI_selectTrials(varargin)
getFIRA_ecodesByName function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
This function is called by:
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig