Description of plotGUI_scatter
FIRA / gui/ plotMenu / plotGUI_scatter.m
plotGUI_scatter
PURPOSE
plotGUI_scatter Application M-file for plotGUI_scatter.fig
SYNOPSIS
function varargout = plotGUI_scatter(varargin)
DESCRIPTION
 plotGUI_scatter Application M-file for plotGUI_scatter.fig
    FIG = plotGUI_scatter launch plotGUI_scatter GUI.
    plotGUI_scatter('callback_name', ...) invoke the named callback.
 GUI wrapper for plotFIRA_scatter
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
plotGUI_scatter plotGUI_scatter Application M-file for plotGUI_scatter.fig
getGUI_pmString string_ = getGUI_pmString(menu_handle)
gsGUI_ecodeValuesByName function varargout = gsGUI_ecodeValuesByName(key, varargin)
gsGUI_saveSettings
gsGUI_selectByUniqueID function varargout = gsGUI_selectByUniqueID(key, varargin)
gsGUI_selectTrials function varargout = gsGUI_selectTrials(varargin)
plotFIRA_scatter
This function is called by:
plotGUI_scatter plotGUI_scatter Application M-file for plotGUI_scatter.fig