Description of checkGUI_editValue
FIRA / gui/ utilities / checkGUI_editValue.m
checkGUI_editValue
PURPOSE
function checkGUI_editValue(h, min_val, max_val)
SYNOPSIS
function checkGUI_editValue(h, min_val, max_val)
DESCRIPTION
 function checkGUI_editValue(h, min_val, max_val)
 called when any value in an edit box is changed...
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
This function is called by: