Description of gsGUI_selectByUniqueID
FIRA / gui/ utilities / gsGUI_selectByUniqueID.m
gsGUI_selectByUniqueID
PURPOSE
function varargout = gsGUI_selectByUniqueID(key, varargin)
SYNOPSIS
function varargout = gsGUI_selectByUniqueID(key, varargin)
DESCRIPTION
 function varargout = gsGUI_selectByUniqueID(key, varargin)
   assumes there is a GUI with a menu
   'set' makes the menu entries the "id" ecode fields from FIRA
   'get' gets a matrix of selection arrays of the given trials for
       the unique values of the chosen id
 Usage:
                    gsGUI_selectByUniqueID('setf', menu_h, default_value);
   [Lsb, uniques] = gsGUI_selectByUniqueID('getf', menu_h, trials, max_n, include_list);
CROSS-REFERENCE INFORMATION
This function calls:
getGUI_pmString string_ = getGUI_pmString(menu_handle)
getFIRA_ecodeNames function names_ = getFIRA_ecodeNames(type)
selectFIRA_trialsByUniqueID function [Lsb_, uniques_] = selectFIRA_trialsByUniqueID(name, trials)
This function is called by:
plotGUI_deviations plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_eyePosition plotGUI_eyePosition Application M-file for plotFIRA_eyes.fig
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
plotGUI_neurometricROCT plotGUI_neurometricROC Application M-file for plotGUI_neurometricROCT.fig
plotGUI_polarTC plotGUI_rasterTC Application M-file for plotGUI_polarTC.fig
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_quickT plotGUI_quickT Application M-file for plotGUI_quickT.fig
plotGUI_raster plotGUI_rasterTC Application M-file for plotGUI_raster.fig
plotGUI_scatter plotGUI_scatter Application M-file for plotGUI_scatter.fig