Description of gsGUI_ecodeTimesByName
FIRA / gui/ utilities / gsGUI_ecodeTimesByName.m
gsGUI_ecodeTimesByName
PURPOSE
function varargout = gsGUI_ecodeTimesByName(key, varargin)
SYNOPSIS
function varargout = gsGUI_ecodeTimesByName(key, varargin)
DESCRIPTION
 function varargout = gsGUI_ecodeTimesByName(key, varargin)
   assumes there is a GUI with a menu and an edit box
   'set' makes the menu entries the "time" ecode fields from FIRA
   'get' gets an array of times for each of the given trials
       of the time of the event chosen in the menu plus the offset in
       the text box
 Usage:
              gsGUI_ecodeTimesByName('setf', menu_h, default_index, ...
                                       edit_h, edit_value);
      times = gsGUI_ecodeTimesByName('getf', menu_h, edit_h, ...
                                       trials);
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
getGUI_pmString string_ = getGUI_pmString(menu_handle)
getFIRA_ecodeNames function names_ = getFIRA_ecodeNames(type)
getFIRA_ecodesByName function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
This function is called by:
plotGUI_deviations plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_eyePosition plotGUI_eyePosition Application M-file for plotFIRA_eyes.fig
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
plotGUI_neurometricROCT plotGUI_neurometricROC Application M-file for plotGUI_neurometricROCT.fig
plotGUI_polarTC plotGUI_rasterTC Application M-file for plotGUI_polarTC.fig
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_quickT plotGUI_quickT Application M-file for plotGUI_quickT.fig
plotGUI_raster plotGUI_rasterTC Application M-file for plotGUI_raster.fig
plotGUI_summary plotGUI_summary Application M-file for plotGUI_summary.fig