Description of gsGUI_ecodeValuesByName
FIRA / gui/ utilities / gsGUI_ecodeValuesByName.m
gsGUI_ecodeValuesByName
PURPOSE
function varargout = gsGUI_ecodeValuesByName(key, varargin)
SYNOPSIS
function varargout = gsGUI_ecodeValuesByName(key, varargin)
DESCRIPTION
 function varargout = gsGUI_ecodeValuesByName(key, varargin)
   assumes there is a GUI with a menu and an edit box
   'set' makes the menu entries the "value" ecode fields from FIRA
   'get' gets the array of values
 Usage:
               gsGUI_ecodeValuesByName('setf', menu_h, default_index);
      values = gsGUI_ecodeValuesByName('getf', menu_h, trials)
CROSS-REFERENCE INFORMATION
This function calls:
getGUI_pmString string_ = getGUI_pmString(menu_handle)
getFIRA_ecodeNames function names_ = getFIRA_ecodeNames(type)
getFIRA_ecodesByName function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
This function is called by:
plotGUI_scatter plotGUI_scatter Application M-file for plotGUI_scatter.fig
plotGUI_summary plotGUI_summary Application M-file for plotGUI_summary.fig