Description of getFIRA_ecodeNames
FIRA / utilities / getFIRA_ecodeNames.m
getFIRA_ecodeNames
PURPOSE
function names_ = getFIRA_ecodeNames(type)
SYNOPSIS
function names_ = getFIRA_ecodeNames(type)
DESCRIPTION
 function names_ = getFIRA_ecodeNames(type)
 returns a cell array of (string) names.
 Argument:
   type ... type of data ('id', 'value', 'time')
 If no arg is given then all names are returned.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gsGUI_ecodeIDsByName function varargout = gsGUI_ecodeIDsByName(key, varargin)
gsGUI_ecodeTimesByName function varargout = gsGUI_ecodeTimesByName(key, varargin)
gsGUI_ecodeValuesByName function varargout = gsGUI_ecodeValuesByName(key, varargin)
gsGUI_selectByUniqueID function varargout = gsGUI_selectByUniqueID(key, varargin)
gsGUI_selectTrials function varargout = gsGUI_selectTrials(varargin)