Description of plotFIRA_neurometricROC
FIRA / utilities / plotFIRA_neurometricROC.m
plotFIRA_neurometricROC
PURPOSE
function [fits_, stats_] = plotFIRA_neurometricROC(...
SYNOPSIS
function [fits_, stats_] = plotFIRA_neurometricROC(trials, Lsd, Lsc, cohs, spikei, begin_times, end_times,lambda, mainaxis, cohhs)
DESCRIPTION
function [fits_, stats_] = plotFIRA_neurometricROC(...
    trials, Lsd, Lsc, cohs, spikei, begin_times, end_times, ...
    mainaxis, cohaxes, cohhs)
   Arguments:
       trials      ... list of trials in FIRA
       Lsd         ... mx2 selection array, cols are directions
       Lsc         ... mxn selection array, cols are cohs
       cohs        ... coh values corresponding to cols of Lsc
       spikei      ... spike index (scalar)
       begin_times ... begin time of trial epoch
       end_times   ... end time of trial epoch
       lambda      ... optional value of lambda (lapse) to send to fit
       mainaxis    ... axis to plot % correct and fits
       cohhs       ... handles to plot objects
   Returns:
       fits_       ... best fit & sem of alpha, beta, lambda
       stats_      ... LLR, p
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
This function is called by:
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
plotFIRA_neurometricROCT function fits_ = plotFIRA_neurometricROCT(trials, Lsd, Lsc, ...