Description of saveFIRA
FIRA / utilities / saveFIRA.m
saveFIRA
PURPOSE
function saveFIRA(filename)
SYNOPSIS
function saveFIRA(filename)
DESCRIPTION
 function saveFIRA(filename)
 Saves a copy of FIRA called "data" into
   the given file. Ignores field FIRA.raw
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bFile function bFile(file_in, file_type, spm, file_out, spike_list, ...
plotGUI plotGUI Application M-file for plotGUI.fig
combineFIRA_files function combineFIRA_files(fileout, varargin)