Description of gsGUI_selectSpike
FIRA / gui/ utilities / gsGUI_selectSpike.m
gsGUI_selectSpike
PURPOSE
function varargout = gsGUI_selectSpike(key, varargin)
SYNOPSIS
function varargout = gsGUI_selectSpike(key, varargin)
DESCRIPTION
 function varargout = gsGUI_selectSpike(key, varargin)
   assumes there is a GUI with a menu
   'set' makes the menu entries the ids of spikes in FIRA
   'get' gets the index of the chosen spike id
 Usage:
              gsGUI_selectSpike('setf', menu_h);
      index = gsGUI_selectSpike('getf', menu_h);
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
This function is called by: