Description of gsGUI_selectTrials
FIRA / gui/ utilities / gsGUI_selectTrials.m
gsGUI_selectTrials
PURPOSE
function varargout = gsGUI_selectTrials(varargin)
SYNOPSIS
function varargout = gsGUI_selectTrials(varargin)
DESCRIPTION
 function varargout = gsGUI_selectTrials(varargin)
 Sets up a modal dialog that is used to
 make an "Larray" from FIRA data. Typically is
 given the list of "id" column names from
 FIRA.ecodes and sets up a series of rows
 of radiobuttons, each row corresponding to
 all possible values of the given id.
 WARNING
 -------
 BE SURE TO SET THE OUTPUT OF INITF TO HANDLES.SELECT
 Usage:
 sel_ = gsGUI_selectTrials('initf', select_button_h, creator)
        ... initializes the sel_ struct and sets up the
               appropriate callbacks
 gsGUI_selectTrials('setf', plot_h, handles)
        ... invokes the GUI to make the cell array of new values
               (array for each id) used to generate the Larray
               this is set up automatically by initf
 trials = gsGUI_selectTrials('getf', newS, curslider_handle, histslider_handle)
        ... generates the list of selected trials from FIRA based on the
               gui
 Callbacks:
  gsGUI_Larray('rb_cb',     h, ind, hdata)
  gsGUI_Larray('ok_cb',     hdata)
  gsGUI_Larray('cancel_cb', hdata)
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
getFIRA_ecodeColumnByName function column_ = getFIRA_ecodeColumnByName(name, type)
getFIRA_ecodeNames function names_ = getFIRA_ecodeNames(type)
getFIRA_uniqueEcodeValues function ids_ = getFIRA_uniqueEcodeIDs(names)
This function is called by:
plotGUI_deviations plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_eyePosition plotGUI_eyePosition Application M-file for plotFIRA_eyes.fig
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
plotGUI_neurometricROCT plotGUI_neurometricROC Application M-file for plotGUI_neurometricROCT.fig
plotGUI_polarTC plotGUI_rasterTC Application M-file for plotGUI_polarTC.fig
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_quickT plotGUI_quickT Application M-file for plotGUI_quickT.fig
plotGUI_raster plotGUI_rasterTC Application M-file for plotGUI_raster.fig
plotGUI_scatter plotGUI_scatter Application M-file for plotGUI_scatter.fig