Description of gsGUI_saveSettings
FIRA / gui/ utilities / gsGUI_saveSettings.m
gsGUI_saveSettings
PURPOSE
SYNOPSIS
function varargout = gsGUI_saveSettings(varargin)
DESCRIPTION
 stores/loads the current state of the interface
 store info in a file called settings_<name>.mat, placed in
   FS_labMfilePath('FIRA', 'gui', 'figs')
 Assumptions:
   parent function is called "getGUI_<name>" and
       it has a function named "update_cb"
   FS_* tools are in the path
 Usage for setup:
  handles = gsGUI_saveSettings('setf', h, handles, name, ss)
 Usage for callback:
   gsGUI_saveSettings('callback')
CROSS-REFERENCE INFORMATION
This function calls:
get (analog) function val_ = get(a, property)
get (awdData) function val_ = get(a, property)
get (dio) function val_ = get(d, property)
get (ecodes) function val_ = get(e, property)
get (kbdData) function val_ = get(k, property)
get (lpHIDData) function val_ = get(lp, property)
get (matCmds) function val_ = get(a, property)
get (spikes) function val_ = get(s, property)
get (trial) function val_ = get(t, property)
This function is called by:
plotGUI_deviations plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_eyePosition plotGUI_eyePosition Application M-file for plotFIRA_eyes.fig
plotGUI_neurometricROC plotGUI_neurometricROC Application M-file for plotGUI_neurometricROC.fig
plotGUI_neurometricROCT plotGUI_neurometricROC Application M-file for plotGUI_neurometricROCT.fig
plotGUI_polarTC plotGUI_rasterTC Application M-file for plotGUI_polarTC.fig
plotGUI_psychometric plotGUI_neurometricROC Application M-file for plotGUI_psychometric.fig
plotGUI_quickT plotGUI_quickT Application M-file for plotGUI_quickT.fig
plotGUI_raster plotGUI_rasterTC Application M-file for plotGUI_raster.fig
plotGUI_scatter plotGUI_scatter Application M-file for plotGUI_scatter.fig