Description of gsGUI_ecodeIDsByName
FIRA / gui/ utilities / gsGUI_ecodeIDsByName.m
gsGUI_ecodeIDsByName
PURPOSE
function varargout = gsGUI_ecodeIDsByName(key, varargin)
SYNOPSIS
function varargout = gsGUI_ecodeIDsByName(key, varargin)
DESCRIPTION
 function varargout = gsGUI_ecodeIDsByName(key, varargin)
   assumes there is a GUI with a menu and an edit box
   'setf' makes the menu entries the "id" ecode fields from FIRA
   'getf' gets an array of ids for each of the given trials
 Usage:
              gsGUI_ecodeIDsByName('setf', menu_h, default_index);
      times = gsGUI_ecodeIDsByName('getf', menu_h, trials);
CROSS-REFERENCE INFORMATION
This function calls:
getGUI_pmString string_ = getGUI_pmString(menu_handle)
getFIRA_ecodeNames function names_ = getFIRA_ecodeNames(type)
getFIRA_ecodesByName function ecodes_ = getFIRA_ecodeTimesByName(name, type, trials)
This function is called by:
plotGUI_neurometricROCT plotGUI_neurometricROC Application M-file for plotGUI_neurometricROCT.fig
plotGUI_quickT plotGUI_quickT Application M-file for plotGUI_quickT.fig
plotGUI_summary plotGUI_summary Application M-file for plotGUI_summary.fig